trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: true
arrowParens: "always"
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: false
parser: "babel"
printWidth: 80
quoteProps: "consistent"
