    name: Deploy to GitHub Pages
    on:
        push:
            branches:
            - master
    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Set ignore warning flag
          env: 
            CI: false
          
        - name: Yarn install
          uses: Borales/actions-yarn@v2.3.0
          with:
            cmd: install
            
        - name: Yarn build    
          uses: Borales/actions-yarn@v2.3.0
          with:
            cmd: build
            
#         - name: Build
#           run: |
#             npm install
#             CI='' npm run build
          env:
            REACT_APP_FIREBASE_KEY: ${{ secrets.REACT_APP_FIREBASE_KEY }}
            run: echo "--hello from CI script--"
            REACT_APP_FIREBASE_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_DOMAIN }}
            REACT_APP_FIREBASE_DATABASE: ${{ secrets.REACT_APP_FIREBASE_DATABASE }}
            REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
            REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
            REACT_APP_FIREBASE_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_SENDER_ID }}
            REACT_APP_MESSAGING_APP_ID: ${{ secrets.REACT_APP_MESSAGING_APP_ID }}

        - name: Deploy to gh-pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./build
